#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro ingress logs"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ingress::logs
}

run() {
  core "$@"
}

run "$@"
