#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro ingress restart"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ingress::service_restart
}

run() {
  core "$@"
}

run "$@"
