#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro ingress service reload"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ingress::service_reload
}

run() {
  core "$@"
}

run "$@"
